name: Build

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Cloudflare Worker types
        run: pnpm run cf-typegen:ci

      - name: Build
        run: pnpm run build

      - name: Code check
        run: pnpm run lint && pnpm run format:check

      - name: Clone backend
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: "pulsate-dev/pulsate"
          path: "backend/"

      - name: Build backend
        working-directory: "./backend"
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          touch .env

      - name: Run E2E test
        env:
          CLOUDFLARE_ENV: ci
        run: |
          set -e
          pnpm playwright install chromium --only-shell
          cd backend && pnpm start & id=$!
          pnpm e2e
          kill "$id"
